import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "dist",
      ".output",
      ".vinxi",
      // Generated by the Netlify adapter at build time.
      ".netlify",
      // Vendored design handoff — reference material, not our source.
      "Room booking system dashboard",
      // Generated by the TanStack router plugin.
      "src/routeTree.gen.ts",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
          patterns: [
            {
              group: ["**/__fixtures__/**"],
              message:
                "Seed rows are server-only. Route loaders run in the browser, so importing fixtures from client-reachable code compiles every guest's name, email and phone into dist/client — the chunk the landing page serves anonymous visitors. Read them through a server function in `lib/bookings-data.ts`. Tests may import them directly.",
            },
            {
              group: ["**/lib/db", "**/lib/schema"],
              message:
                "The database client is server-only: it reads DATABASE_URL, a production credential, and this repo is public. Only modules whose every export is a server function may import it (bookings-data.ts, invites.ts, auth.ts). Importing it from client-reachable code puts the connection string one careless line away from dist/client.",
            },
            {
              group: ["**/lib/roster", "**/lib/password"],
              message:
                "The roster store is server-only: it reads the database and is the only code that can read a password hash. `lib/team.ts` holds the rules and is safe to import from anywhere; this holds the rows. Importing it from client-reachable code is how #12 shipped `krc-admin` to every browser.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    // The fixtures exist to be derived against, and the suite is where that
    // happens. `bookings-data.ts` also reads them, as the no-DATABASE_URL
    // fallback that keeps local dev and the tests working without a database.
    //
    // These three are the server boundary: every export is a `createServerFn`
    // handler, so nothing here reaches `dist/client`. They are the only modules
    // allowed to touch `lib/db` — `db.ts` and `schema.ts` themselves included,
    // since one imports the other.
    files: [
      "src/lib/**/*.test.ts",
      "src/lib/bookings-data.ts",
      "src/lib/invites.ts",
      "src/lib/auth.ts",
      "src/lib/db.ts",
      "src/lib/roster.ts",
      "scripts/**/*.ts",
    ],
    rules: { "no-restricted-imports": "off" },
  },
  {
    // shadcn/ui primitives are vendored in and deliberately export their
    // variant helpers (`buttonVariants`, `useFormField`, …) alongside the
    // component. That trips the fast-refresh rule with nothing to act on.
    files: ["src/components/ui/**/*.tsx"],
    rules: { "react-refresh/only-export-components": "off" },
  },
  eslintPluginPrettier,
);
