// The seed rows every admin screen renders, and the only data the test suite
// derives against. Mirrors the design files.
//
// This lives behind `__fixtures__` for one reason: these rows used to sit in
// `lib/bookings.ts`, which route loaders import, so the bundler compiled every
// guest name and email address into `dist/client` — the chunk an anonymous
// visitor to the landing page downloads. Mock names made that harmless; real
// ones will not. Nothing client-reachable may import this file, and eslint's
// `no-restricted-imports` enforces that rather than trusting the convention.
//
// `bookings-data.ts` reads these today. When the tables land it queries them
// instead, and this file goes back to being what its name says: test fixtures
// and a local seed.

import type { Booking, BookingStatus, Guest, PartyHallEnquiry } from "@/types/booking";
import {
  defaultRoomTiles,
  GST_PCT,
  withAdvance,
  withTier,
  withTotal,
  type BookingData,
} from "@/lib/bookings";

const GUEST_SEED: Omit<Guest, "tier">[] = [
  {
    id: "G-001",
    name: "Aarav Mehta",
    phone: "+91 98110 22334",
    email: "aarav.mehta@example.com",
    city: "New Delhi",
    stays: 6,
    lifetimeValue: 48200,
  },
  {
    id: "G-002",
    name: "Priya Nair",
    phone: "+91 99870 55212",
    email: "priya.nair@example.com",
    city: "Bengaluru",
    stays: 3,
    lifetimeValue: 21400,
  },
  {
    id: "G-003",
    name: "Rohan Verma",
    phone: "+91 90000 78451",
    email: "rohan.verma@example.com",
    city: "Greater Noida",
    stays: 1,
    lifetimeValue: 3400,
  },
  {
    id: "G-004",
    name: "Meera Krishnan",
    phone: "+91 98400 11223",
    email: "meera.krishnan@example.com",
    city: "Chennai",
    stays: 4,
    lifetimeValue: 32600,
  },
  {
    id: "G-005",
    name: "Rohit Kapoor",
    phone: "+91 94140 66789",
    email: "rohit.kapoor@example.com",
    city: "Jaipur",
    stays: 2,
    lifetimeValue: 11800,
  },
  {
    id: "G-006",
    name: "Fatima Sheikh",
    phone: "+91 90050 44120",
    email: "fatima.sheikh@example.com",
    city: "Lucknow",
    stays: 2,
    lifetimeValue: 9600,
  },
  {
    id: "G-007",
    name: "Deepak Rao",
    phone: "+91 99490 33087",
    email: "deepak.rao@example.com",
    city: "Hyderabad",
    stays: 1,
    lifetimeValue: 3400,
  },
  {
    id: "G-008",
    name: "Karan Malhotra",
    phone: "+91 98150 90011",
    email: "karan.malhotra@example.com",
    city: "Chandigarh",
    stays: 1,
    lifetimeValue: 0,
  },
  {
    id: "G-009",
    name: "Vikram Nair",
    phone: "+91 90720 55340",
    email: "vikram.nair@example.com",
    city: "Kochi",
    stays: 1,
    lifetimeValue: 0,
  },
  {
    id: "G-010",
    name: "Sunita Verma",
    phone: "+91 98730 21980",
    email: "sunita.verma@example.com",
    city: "New Delhi",
    stays: 3,
    lifetimeValue: 18900,
  },
  // G-011..G-023: one-off stays backing the late-July occupancy ramp below
  // (medium on the 23rd, high on the 24th, a genuine full house on the
  // 25th/26th) — real bookings the occupancy band legend can reach through
  // `occupiedRoomsOn`, replacing the deleted JULY_2026_OCCUPANCY table.
  {
    id: "G-011",
    name: "Anjali Bhatt",
    phone: "+91 98200 11234",
    email: "anjali.bhatt@example.com",
    city: "Ahmedabad",
    stays: 1,
    lifetimeValue: 5040,
  },
  {
    id: "G-012",
    name: "Siddharth Rao",
    phone: "+91 98200 22345",
    email: "siddharth.rao@example.com",
    city: "Pune",
    stays: 1,
    lifetimeValue: 5040,
  },
  {
    id: "G-013",
    name: "Neha Joshi",
    phone: "+91 98200 33456",
    email: "neha.joshi@example.com",
    city: "Indore",
    stays: 1,
    lifetimeValue: 5040,
  },
  {
    id: "G-014",
    name: "Arjun Menon",
    phone: "+91 98200 44567",
    email: "arjun.menon@example.com",
    city: "Kozhikode",
    stays: 1,
    lifetimeValue: 5040,
  },
  {
    id: "G-015",
    name: "Kavya Iyer",
    phone: "+91 98200 55678",
    email: "kavya.iyer@example.com",
    city: "Coimbatore",
    stays: 1,
    lifetimeValue: 5040,
  },
  {
    id: "G-016",
    name: "Rahul Chawla",
    phone: "+91 98200 66789",
    email: "rahul.chawla@example.com",
    city: "Amritsar",
    stays: 1,
    lifetimeValue: 5040,
  },
  {
    id: "G-017",
    name: "Divya Pillai",
    phone: "+91 98200 77890",
    email: "divya.pillai@example.com",
    city: "Thiruvananthapuram",
    stays: 1,
    lifetimeValue: 3780,
  },
  {
    id: "G-018",
    name: "Aditya Desai",
    phone: "+91 98200 88901",
    email: "aditya.desai@example.com",
    city: "Surat",
    stays: 1,
    lifetimeValue: 3780,
  },
  {
    id: "G-019",
    name: "Ishita Bose",
    phone: "+91 98200 99012",
    email: "ishita.bose@example.com",
    city: "Kolkata",
    stays: 1,
    lifetimeValue: 3780,
  },
  {
    id: "G-020",
    name: "Varun Khanna",
    phone: "+91 98200 10123",
    email: "varun.khanna@example.com",
    city: "Ludhiana",
    stays: 1,
    lifetimeValue: 3780,
  },
  {
    id: "G-021",
    name: "Pooja Sharma",
    phone: "+91 98200 21234",
    email: "pooja.sharma@example.com",
    city: "Bhopal",
    stays: 1,
    lifetimeValue: 2520,
  },
  {
    id: "G-022",
    name: "Manish Iyer",
    phone: "+91 98200 32345",
    email: "manish.iyer@example.com",
    city: "Madurai",
    stays: 1,
    lifetimeValue: 2520,
  },
  {
    id: "G-023",
    name: "Sneha Kapoor",
    phone: "+91 98200 43456",
    email: "sneha.kapoor@example.com",
    city: "Nagpur",
    stays: 1,
    lifetimeValue: 2520,
  },
];

const BOOKINGS: Booking[] = [
  withTotal({
    id: "KRC-20260714-001",
    guestId: "G-001",
    roomNo: "102",
    roomType: "deluxe",
    checkIn: "2026-07-14",
    checkOut: "2026-07-17",
    urn: 3,
    source: "direct",
    mealPlan: "CP",
    revenue: {
      room: 4500,
      earlyCheckIn: 0,
      lateCheckOut: 0,
      other: 0,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 5040,
      otaCollection: 0,
      otaCommission: 0,
      complimentary: 0,
      pending: 0,
    },
    status: "checked_in",
    createdAt: "2026-07-10T09:12:00.000Z",
  }),
  withTotal({
    id: "KRC-20260715-002",
    guestId: "G-002",
    roomNo: "205",
    roomType: "deluxe_balcony",
    checkIn: "2026-07-15",
    checkOut: "2026-07-16",
    urn: 1,
    source: "booking_com",
    mealPlan: "EP",
    revenue: {
      room: 1700,
      earlyCheckIn: 0,
      lateCheckOut: 300,
      other: 0,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 0,
      otaCollection: 2240,
      otaCommission: 336,
      complimentary: 0,
      pending: 0,
    },
    status: "confirmed",
    createdAt: "2026-07-12T14:40:00.000Z",
  }),
  withTotal({
    id: "KRC-20260715-003",
    guestId: "G-003",
    roomNo: null,
    roomType: "deluxe",
    checkIn: "2026-07-20",
    checkOut: "2026-07-22",
    urn: 2,
    source: "phone",
    mealPlan: "MAP",
    revenue: {
      room: 3000,
      earlyCheckIn: 0,
      lateCheckOut: 0,
      other: 0,
      discount: 200,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 0,
      otaCollection: 0,
      otaCommission: 0,
      complimentary: 0,
      pending: 3136,
    },
    status: "pending_payment",
    createdAt: "2026-07-15T08:05:00.000Z",
  }),
  withTotal({
    id: "KRC-20260714-004",
    guestId: "G-004",
    roomNo: "112",
    roomType: "deluxe",
    checkIn: "2026-07-13",
    checkOut: "2026-07-16",
    urn: 3,
    source: "booking_com",
    mealPlan: "MAP",
    revenue: {
      room: 4500,
      earlyCheckIn: 0,
      lateCheckOut: 0,
      other: 600,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 0,
      otaCollection: 5712,
      otaCommission: 856,
      complimentary: 0,
      pending: 0,
    },
    status: "checked_in",
    createdAt: "2026-07-09T11:20:00.000Z",
  }),
  withTotal({
    id: "KRC-20260711-005",
    guestId: "G-005",
    roomNo: "108",
    roomType: "deluxe",
    checkIn: "2026-07-11",
    checkOut: "2026-07-13",
    urn: 2,
    source: "walk_in",
    mealPlan: "EP",
    revenue: {
      room: 3000,
      earlyCheckIn: 0,
      lateCheckOut: 500,
      other: 0,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 3920,
      otaCollection: 0,
      otaCommission: 0,
      complimentary: 0,
      pending: 0,
    },
    status: "checked_out",
    createdAt: "2026-07-08T16:30:00.000Z",
  }),
  withTotal({
    id: "KRC-20260710-006",
    guestId: "G-006",
    roomNo: "207",
    roomType: "deluxe_balcony",
    checkIn: "2026-07-10",
    checkOut: "2026-07-12",
    urn: 2,
    source: "goibibo",
    mealPlan: "CP",
    revenue: {
      room: 3400,
      earlyCheckIn: 0,
      lateCheckOut: 0,
      other: 300,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 0,
      otaCollection: 4144,
      otaCommission: 622,
      complimentary: 0,
      pending: 0,
    },
    status: "checked_out",
    createdAt: "2026-07-06T10:15:00.000Z",
  }),
  withTotal({
    id: "KRC-20260714-007",
    guestId: "G-007",
    roomNo: "201",
    roomType: "deluxe_balcony",
    checkIn: "2026-07-16",
    checkOut: "2026-07-18",
    urn: 2,
    source: "direct",
    mealPlan: "EP",
    revenue: {
      room: 3400,
      earlyCheckIn: 0,
      lateCheckOut: 0,
      other: 0,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 0,
      otaCollection: 0,
      otaCommission: 0,
      complimentary: 0,
      pending: 3808,
    },
    status: "confirmed",
    createdAt: "2026-07-14T13:00:00.000Z",
  }),
  withTotal({
    id: "KRC-20260715-008",
    guestId: "G-008",
    roomNo: null,
    roomType: "deluxe",
    checkIn: "2026-07-15",
    checkOut: "2026-07-17",
    urn: 2,
    source: "agoda",
    mealPlan: "EP",
    revenue: {
      room: 3000,
      earlyCheckIn: 0,
      lateCheckOut: 0,
      other: 0,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 0,
      otaCollection: 0,
      otaCommission: 0,
      complimentary: 0,
      pending: 0,
    },
    status: "cancelled",
    createdAt: "2026-07-13T19:45:00.000Z",
  }),
  withTotal({
    id: "KRC-20260713-009",
    guestId: "G-009",
    roomNo: null,
    roomType: "deluxe",
    checkIn: "2026-07-13",
    checkOut: "2026-07-14",
    urn: 1,
    source: "direct",
    mealPlan: "EP",
    revenue: {
      room: 1500,
      earlyCheckIn: 0,
      lateCheckOut: 0,
      other: 0,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 0,
      otaCollection: 0,
      otaCommission: 0,
      complimentary: 0,
      pending: 0,
    },
    status: "no_show",
    createdAt: "2026-07-12T21:10:00.000Z",
  }),
  withTotal({
    id: "KRC-20260712-010",
    guestId: "G-010",
    roomNo: "104",
    roomType: "deluxe",
    checkIn: "2026-07-12",
    checkOut: "2026-07-15",
    urn: 3,
    source: "phone",
    mealPlan: "CP",
    revenue: {
      room: 4500,
      earlyCheckIn: 400,
      lateCheckOut: 0,
      other: 150,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 5656,
      otaCollection: 0,
      otaCommission: 0,
      complimentary: 0,
      pending: 0,
    },
    status: "checked_out",
    createdAt: "2026-07-05T09:40:00.000Z",
  }),
  // Late-July occupancy ramp — real bookings reaching medium (23rd), high
  // (24th), and a genuine full house (25th/26th) through `occupiedRoomsOn`,
  // across the 13 sellable rooms (room 105 is seeded under maintenance; see
  // `ROOM_STATE_SEED`). Chosen to not collide with any other test's
  // hardcoded date. All `confirmed` — future bookings, not yet checked in.
  withTotal({
    id: "KRC-20260723-011",
    guestId: "G-011",
    roomNo: "101",
    roomType: "deluxe",
    checkIn: "2026-07-23",
    checkOut: "2026-07-27",
    urn: 4,
    source: "direct",
    mealPlan: "CP",
    revenue: {
      room: 18000,
      earlyCheckIn: 0,
      lateCheckOut: 0,
      other: 0,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 20160,
      otaCollection: 0,
      otaCommission: 0,
      complimentary: 0,
      pending: 0,
    },
    status: "confirmed",
    createdAt: "2026-07-18T10:00:00.000Z",
  }),
  withTotal({
    id: "KRC-20260723-012",
    guestId: "G-012",
    roomNo: "102",
    roomType: "deluxe",
    checkIn: "2026-07-23",
    checkOut: "2026-07-27",
    urn: 4,
    source: "direct",
    mealPlan: "CP",
    revenue: {
      room: 18000,
      earlyCheckIn: 0,
      lateCheckOut: 0,
      other: 0,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 20160,
      otaCollection: 0,
      otaCommission: 0,
      complimentary: 0,
      pending: 0,
    },
    status: "confirmed",
    createdAt: "2026-07-18T10:05:00.000Z",
  }),
  withTotal({
    id: "KRC-20260723-013",
    guestId: "G-013",
    roomNo: "103",
    roomType: "deluxe",
    checkIn: "2026-07-23",
    checkOut: "2026-07-27",
    urn: 4,
    source: "direct",
    mealPlan: "CP",
    revenue: {
      room: 18000,
      earlyCheckIn: 0,
      lateCheckOut: 0,
      other: 0,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 20160,
      otaCollection: 0,
      otaCommission: 0,
      complimentary: 0,
      pending: 0,
    },
    status: "confirmed",
    createdAt: "2026-07-18T10:10:00.000Z",
  }),
  withTotal({
    id: "KRC-20260723-014",
    guestId: "G-014",
    roomNo: "104",
    roomType: "deluxe",
    checkIn: "2026-07-23",
    checkOut: "2026-07-27",
    urn: 4,
    source: "direct",
    mealPlan: "CP",
    revenue: {
      room: 18000,
      earlyCheckIn: 0,
      lateCheckOut: 0,
      other: 0,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 20160,
      otaCollection: 0,
      otaCommission: 0,
      complimentary: 0,
      pending: 0,
    },
    status: "confirmed",
    createdAt: "2026-07-18T10:15:00.000Z",
  }),
  withTotal({
    id: "KRC-20260723-015",
    guestId: "G-015",
    roomNo: "201",
    roomType: "deluxe",
    checkIn: "2026-07-23",
    checkOut: "2026-07-27",
    urn: 4,
    source: "direct",
    mealPlan: "CP",
    revenue: {
      room: 18000,
      earlyCheckIn: 0,
      lateCheckOut: 0,
      other: 0,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 20160,
      otaCollection: 0,
      otaCommission: 0,
      complimentary: 0,
      pending: 0,
    },
    status: "confirmed",
    createdAt: "2026-07-18T10:20:00.000Z",
  }),
  withTotal({
    id: "KRC-20260723-016",
    guestId: "G-016",
    roomNo: "202",
    roomType: "deluxe",
    checkIn: "2026-07-23",
    checkOut: "2026-07-27",
    urn: 4,
    source: "direct",
    mealPlan: "CP",
    revenue: {
      room: 18000,
      earlyCheckIn: 0,
      lateCheckOut: 0,
      other: 0,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 20160,
      otaCollection: 0,
      otaCommission: 0,
      complimentary: 0,
      pending: 0,
    },
    status: "confirmed",
    createdAt: "2026-07-18T10:25:00.000Z",
  }),
  withTotal({
    id: "KRC-20260724-017",
    guestId: "G-017",
    roomNo: "203",
    roomType: "deluxe",
    checkIn: "2026-07-24",
    checkOut: "2026-07-27",
    urn: 3,
    source: "direct",
    mealPlan: "CP",
    revenue: {
      room: 13500,
      earlyCheckIn: 0,
      lateCheckOut: 0,
      other: 0,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 15120,
      otaCollection: 0,
      otaCommission: 0,
      complimentary: 0,
      pending: 0,
    },
    status: "confirmed",
    createdAt: "2026-07-19T10:00:00.000Z",
  }),
  withTotal({
    id: "KRC-20260724-018",
    guestId: "G-018",
    roomNo: "204",
    roomType: "deluxe",
    checkIn: "2026-07-24",
    checkOut: "2026-07-27",
    urn: 3,
    source: "direct",
    mealPlan: "CP",
    revenue: {
      room: 13500,
      earlyCheckIn: 0,
      lateCheckOut: 0,
      other: 0,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 15120,
      otaCollection: 0,
      otaCommission: 0,
      complimentary: 0,
      pending: 0,
    },
    status: "confirmed",
    createdAt: "2026-07-19T10:05:00.000Z",
  }),
  withTotal({
    id: "KRC-20260724-019",
    guestId: "G-019",
    roomNo: "106",
    roomType: "deluxe_balcony",
    checkIn: "2026-07-24",
    checkOut: "2026-07-27",
    urn: 3,
    source: "direct",
    mealPlan: "CP",
    revenue: {
      room: 13500,
      earlyCheckIn: 0,
      lateCheckOut: 0,
      other: 0,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 15120,
      otaCollection: 0,
      otaCommission: 0,
      complimentary: 0,
      pending: 0,
    },
    status: "confirmed",
    createdAt: "2026-07-19T10:10:00.000Z",
  }),
  withTotal({
    id: "KRC-20260724-020",
    guestId: "G-020",
    roomNo: "107",
    roomType: "deluxe_balcony",
    checkIn: "2026-07-24",
    checkOut: "2026-07-27",
    urn: 3,
    source: "direct",
    mealPlan: "CP",
    revenue: {
      room: 13500,
      earlyCheckIn: 0,
      lateCheckOut: 0,
      other: 0,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 15120,
      otaCollection: 0,
      otaCommission: 0,
      complimentary: 0,
      pending: 0,
    },
    status: "confirmed",
    createdAt: "2026-07-19T10:15:00.000Z",
  }),
  withTotal({
    id: "KRC-20260725-021",
    guestId: "G-021",
    roomNo: "205",
    roomType: "deluxe",
    checkIn: "2026-07-25",
    checkOut: "2026-07-27",
    urn: 2,
    source: "direct",
    mealPlan: "CP",
    revenue: {
      room: 9000,
      earlyCheckIn: 0,
      lateCheckOut: 0,
      other: 0,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 10080,
      otaCollection: 0,
      otaCommission: 0,
      complimentary: 0,
      pending: 0,
    },
    status: "confirmed",
    createdAt: "2026-07-20T10:00:00.000Z",
  }),
  withTotal({
    id: "KRC-20260725-022",
    guestId: "G-022",
    roomNo: "206",
    roomType: "deluxe_balcony",
    checkIn: "2026-07-25",
    checkOut: "2026-07-27",
    urn: 2,
    source: "direct",
    mealPlan: "CP",
    revenue: {
      room: 9000,
      earlyCheckIn: 0,
      lateCheckOut: 0,
      other: 0,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 10080,
      otaCollection: 0,
      otaCommission: 0,
      complimentary: 0,
      pending: 0,
    },
    status: "confirmed",
    createdAt: "2026-07-20T10:05:00.000Z",
  }),
  withTotal({
    id: "KRC-20260725-023",
    guestId: "G-023",
    roomNo: "207",
    roomType: "deluxe_balcony",
    checkIn: "2026-07-25",
    checkOut: "2026-07-27",
    urn: 2,
    source: "direct",
    mealPlan: "CP",
    revenue: {
      room: 9000,
      earlyCheckIn: 0,
      lateCheckOut: 0,
      other: 0,
      discount: 0,
      taxPct: GST_PCT,
    },
    collection: {
      paidToHotel: 10080,
      otaCollection: 0,
      otaCommission: 0,
      complimentary: 0,
      pending: 0,
    },
    status: "confirmed",
    createdAt: "2026-07-20T10:10:00.000Z",
  }),
];

const PARTY_HALL_SEED: Omit<PartyHallEnquiry, "advancePaid">[] = [
  {
    id: "PH-20260622-001",
    title: "Birthday — Nanda family",
    date: "2026-06-21",
    slot: "evening",
    guests: 65,
    package: "Silver",
    addOns: ["Decor", "DJ"],
    status: "completed",
    amount: 52000,
  },
  {
    id: "PH-20260702-002",
    title: "Sangeet — Sharma family",
    date: "2026-07-02",
    slot: "full_day",
    guests: 120,
    package: "Platinum",
    addOns: ["Catering"],
    status: "completed",
    amount: 190000,
  },
  {
    id: "PH-20260730-003",
    title: "Wedding reception — Rao family",
    date: "2026-07-30",
    slot: "evening",
    guests: 150,
    package: "Platinum",
    addOns: ["Catering", "Decor", "DJ"],
    status: "confirmed",
    amount: 240000,
  },
  {
    id: "PH-20260808-004",
    title: "Anniversary — Iyer family",
    date: "2026-08-08",
    slot: "evening",
    guests: 70,
    package: "Gold",
    addOns: ["Catering", "Decor"],
    status: "confirmed",
    amount: 80000,
  },
  {
    id: "PH-20260812-005",
    title: "Birthday — Meera Krishnan",
    date: "2026-08-12",
    slot: "afternoon",
    guests: 55,
    package: "Silver",
    addOns: ["Decor"],
    status: "advance_paid",
    amount: 88000,
  },
  {
    id: "PH-20260816-006",
    title: "Naming ceremony — Pillai family",
    date: "2026-08-16",
    slot: "morning",
    guests: 40,
    package: "Silver",
    addOns: ["Decor"],
    status: "confirmed",
    amount: 36000,
  },
  {
    id: "PH-20260822-007",
    title: "Reception — Priya & Arjun",
    date: "2026-08-22",
    slot: "evening",
    guests: 140,
    package: "Platinum",
    addOns: ["Catering", "Decor"],
    status: "enquiry",
    amount: 0,
  },
  {
    id: "PH-20260829-008",
    title: "Sangeet — Bhatia family",
    date: "2026-08-29",
    slot: "evening",
    guests: 130,
    package: "Platinum",
    addOns: ["Catering", "DJ"],
    status: "confirmed",
    amount: 130000,
  },
  {
    id: "PH-20260905-009",
    title: "Corporate offsite — Nexus Ltd",
    date: "2026-09-05",
    slot: "full_day",
    guests: 90,
    package: "Gold",
    addOns: ["Catering", "AV"],
    status: "quote_sent",
    amount: 110000,
  },
  {
    id: "PH-20260919-010",
    title: "Birthday — Kapoor family",
    date: "2026-09-19",
    slot: "afternoon",
    guests: 60,
    package: "Silver",
    addOns: ["Decor"],
    status: "enquiry",
    amount: 0,
  },
  {
    id: "PH-20260926-011",
    title: "Corporate AGM — Vector Systems",
    date: "2026-09-26",
    slot: "full_day",
    guests: 100,
    package: "Gold",
    addOns: ["Projector", "Lunch Buffet"],
    status: "quote_sent",
    amount: 95000,
  },
  {
    id: "PH-20261003-012",
    title: "Reception — Fernandes & D'Souza",
    date: "2026-10-03",
    slot: "evening",
    guests: 110,
    package: "Platinum",
    addOns: ["Catering", "Decor", "DJ"],
    status: "enquiry",
    amount: 0,
  },
];

/** Tier is derived, never seeded — a badge cannot drift from the stays behind it. */
export const guests: Guest[] = GUEST_SEED.map(withTier);

export const bookings: Booking[] = BOOKINGS;

/** Advance is derived from the quote, at `PARTY_HALL_ADVANCE_PCT`. Wrapped in
 *  an arrow rather than passed directly: `withAdvance` now takes an optional
 *  second `advancePct` parameter, and `Array.prototype.map` calls its
 *  callback with `(item, index, array)` — passed bare, every seed row would
 *  silently get its own array index as the advance percentage. */
export const partyHallEnquiries: PartyHallEnquiry[] = PARTY_HALL_SEED.map((e) => withAdvance(e));

/** The floor board — mutated in place by the no-DB dev path, same convenience
 *  `insertBooking` gives bookings when there is no database to persist to. */
export const rooms = defaultRoomTiles();

/** Slice 3's status-change audit log, no-DB dev path. Not part of
 *  `BookingData` — nothing derives page rows from it yet, it is purely the
 *  fixtures-mutation counterpart of the `booking_status_history` table. */
export interface BookingStatusHistoryRow {
  bookingId: string;
  fromStatus: BookingStatus | null;
  toStatus: BookingStatus;
  changedBy: string | null;
  changedAt: string;
}

export const statusHistory: BookingStatusHistoryRow[] = [];

/** The whole seeded world, in the shape every derivation function reads.
 *  `rooms` and `roomTypeOverrides` are always present here (unlike the
 *  optional fields on `BookingData`), since this is the no-DB dev path's own
 *  mutable store — narrower call sites can rely on that. */
export const fixtures: BookingData & {
  rooms: NonNullable<BookingData["rooms"]>;
  roomTypeOverrides: NonNullable<BookingData["roomTypeOverrides"]>;
  addOnRateOverrides: NonNullable<BookingData["addOnRateOverrides"]>;
  partyHallRateOverrides: NonNullable<BookingData["partyHallRateOverrides"]>;
  statusHistory: BookingStatusHistoryRow[];
} = {
  bookings,
  guests,
  partyHall: partyHallEnquiries,
  rooms,
  roomTypeOverrides: {},
  addOnRateOverrides: {},
  partyHallRateOverrides: {},
  statusHistory,
};
