/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BookingLookupRouteImport } from './routes/booking-lookup'
import { Route as BookRouteImport } from './routes/book'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as InvoiceInvoiceNoRouteImport } from './routes/invoice.$invoiceNo'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRoomsRouteImport } from './routes/admin/rooms'
import { Route as AdminResetPasswordRouteImport } from './routes/admin/reset-password'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminPartyHallRouteImport } from './routes/admin/party-hall'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminGuestsRouteImport } from './routes/admin/guests'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin/forgot-password'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminAcceptInviteRouteImport } from './routes/admin/accept-invite'
import { Route as AdminSettingsInviteRouteImport } from './routes/admin/settings_.invite'

const BookingLookupRoute = BookingLookupRouteImport.update({
  id: '/booking-lookup',
  path: '/booking-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const InvoiceInvoiceNoRoute = InvoiceInvoiceNoRouteImport.update({
  id: '/invoice/$invoiceNo',
  path: '/invoice/$invoiceNo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPartyHallRoute = AdminPartyHallRouteImport.update({
  id: '/party-hall',
  path: '/party-hall',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGuestsRoute = AdminGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAcceptInviteRoute = AdminAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsInviteRoute = AdminSettingsInviteRouteImport.update({
  id: '/settings_/invite',
  path: '/settings/invite',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/book': typeof BookRoute
  '/booking-lookup': typeof BookingLookupRoute
  '/admin/accept-invite': typeof AdminAcceptInviteRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/guests': typeof AdminGuestsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/party-hall': typeof AdminPartyHallRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/invoice/$invoiceNo': typeof InvoiceInvoiceNoRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/settings/invite': typeof AdminSettingsInviteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/booking-lookup': typeof BookingLookupRoute
  '/admin/accept-invite': typeof AdminAcceptInviteRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/guests': typeof AdminGuestsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/party-hall': typeof AdminPartyHallRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/invoice/$invoiceNo': typeof InvoiceInvoiceNoRoute
  '/admin': typeof AdminIndexRoute
  '/admin/settings/invite': typeof AdminSettingsInviteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/book': typeof BookRoute
  '/booking-lookup': typeof BookingLookupRoute
  '/admin/accept-invite': typeof AdminAcceptInviteRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/guests': typeof AdminGuestsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/party-hall': typeof AdminPartyHallRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/invoice/$invoiceNo': typeof InvoiceInvoiceNoRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/settings_/invite': typeof AdminSettingsInviteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/book'
    | '/booking-lookup'
    | '/admin/accept-invite'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/forgot-password'
    | '/admin/guests'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/party-hall'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/reset-password'
    | '/admin/rooms'
    | '/admin/settings'
    | '/invoice/$invoiceNo'
    | '/admin/'
    | '/admin/settings/invite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/booking-lookup'
    | '/admin/accept-invite'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/forgot-password'
    | '/admin/guests'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/party-hall'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/reset-password'
    | '/admin/rooms'
    | '/admin/settings'
    | '/invoice/$invoiceNo'
    | '/admin'
    | '/admin/settings/invite'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/book'
    | '/booking-lookup'
    | '/admin/accept-invite'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/forgot-password'
    | '/admin/guests'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/party-hall'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/reset-password'
    | '/admin/rooms'
    | '/admin/settings'
    | '/invoice/$invoiceNo'
    | '/admin/'
    | '/admin/settings_/invite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BookRoute: typeof BookRoute
  BookingLookupRoute: typeof BookingLookupRoute
  InvoiceInvoiceNoRoute: typeof InvoiceInvoiceNoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/booking-lookup': {
      id: '/booking-lookup'
      path: '/booking-lookup'
      fullPath: '/booking-lookup'
      preLoaderRoute: typeof BookingLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/invoice/$invoiceNo': {
      id: '/invoice/$invoiceNo'
      path: '/invoice/$invoiceNo'
      fullPath: '/invoice/$invoiceNo'
      preLoaderRoute: typeof InvoiceInvoiceNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/party-hall': {
      id: '/admin/party-hall'
      path: '/party-hall'
      fullPath: '/admin/party-hall'
      preLoaderRoute: typeof AdminPartyHallRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/guests': {
      id: '/admin/guests'
      path: '/guests'
      fullPath: '/admin/guests'
      preLoaderRoute: typeof AdminGuestsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/accept-invite': {
      id: '/admin/accept-invite'
      path: '/accept-invite'
      fullPath: '/admin/accept-invite'
      preLoaderRoute: typeof AdminAcceptInviteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings_/invite': {
      id: '/admin/settings_/invite'
      path: '/settings/invite'
      fullPath: '/admin/settings/invite'
      preLoaderRoute: typeof AdminSettingsInviteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAcceptInviteRoute: typeof AdminAcceptInviteRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminGuestsRoute: typeof AdminGuestsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPartyHallRoute: typeof AdminPartyHallRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSettingsInviteRoute: typeof AdminSettingsInviteRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAcceptInviteRoute: AdminAcceptInviteRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminGuestsRoute: AdminGuestsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPartyHallRoute: AdminPartyHallRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSettingsInviteRoute: AdminSettingsInviteRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BookRoute: BookRoute,
  BookingLookupRoute: BookingLookupRoute,
  InvoiceInvoiceNoRoute: InvoiceInvoiceNoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
